### ISSUE TITLE
Regression for test name with single quote character `'`

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [percy/percy-storybook#164] opened 2020-01-06 22:27 UTC
Been using percy storybook for our test suite for over a year now. A test in our test suite started failing last month. The content was always blank.

After investigation / fiddling, renaming the test from `filter override '' & 0` to `filter override empty string & 0` solved the problem (the test isn't blank anymore and contains what's expected -- what's in the storybook-static folder) -- the problematic character seemingly is `'`.

Using `@percy/storybook==3.2.0` and `@storybook/cli==5.1.11` and `@storybook/react==5.1.11`.

Expected resolution would be for either all characters to be correctly supported and/or an appropriate error message describing correct usage if this is intentional, so as not to fail silently.

**Comment by wwilsman** [comment] 2020-02-03 23:09
Hey @Marc-Andre-Rivet!

Looks like this regression was introduced with Storybook since 5.3. Thanks for bringing it to our attention (and sorry it took so long for us to get to).

Will be fixed once #166 is released 😃

**Closed** 2020-02-03 23:09 UTC

**Comment by wwilsman** [comment] 2020-02-18 18:08
Took us long enough, but v3.3.0 is now release with this fix. 👍
