### ISSUE TITLE
Support storybook 5

### ISSUE THREAD

**Issue by kongakong** [percy/percy-storybook#71] opened 2019-03-05 21:58 UTC
https://medium.com/storybookjs/storybook-5-0-db1d0f9c83b8

**Comment by Robdel12** [comment] 2019-03-06 05:39
Hey there! Are you seeing any issues? There shouldn’t be any breaking changes (that we’re aware of) in the v5 release. 

Also, v5 was needed for this PR: https://github.com/percy/percy-storybook/pull/64

**Comment by churichard** [comment] 2019-03-07 21:33
I'm running into an issue where fonts and emojis are not rendering correctly in the Percy snapshot. They render fine when I run Storybook locally, though, so I think it might be a `percy-storybook` issue.

**Comment by thomaswelton** [comment] 2019-03-19 21:28
The issue churichard was describing has now been fixed in the latest version of storybook 5.

I experienced an issue using storybook 5 which resulted in the following error message
`[percy][WARNING] Skipping large file:`

One of our files was 16mb, which is larger than the 15mb percy file limit.
This was due to the fact our webpack config for storybook uses source maps `devtool: cheap-eval-source-map` 

Not sure if this is a result of updates to storybook, but I now just set an `ENV` var when running percy commands and disable source maps entirely.

So I can confirm that percy works for me using storybook 5 🎉

**Comment by timhaines** [comment] 2019-04-05 00:56
@kongakong @churichard @thomaswelton The current version of @percy-io/percy-storybook you are using should support Storybook V5.

Having said that, we have just shipped version 3, under a new package name of @percy/percy-storybook.  It requires Storybook v5.  [Release notes here](https://github.com/percy/percy-storybook/releases/tag/%40percy%2Fpercy-storybook%403.0.0).

**Closed by timhaines** 2019-04-05 00:56 UTC
